apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: myapp
    image: busybox
    command: ["sh", "-c", "echo Starting app... && sleep 3600"]

    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secret

    volumeMounts:
    - name: app-storage
      mountPath: /data

  volumes:
  - name: app-storage
    emptyDir: {}

